### PR TITLE
How to contribute

### PR DESCRIPTION
**Pull request by Tianhao-Shao**

### CODE REVIEW

**Review by peggylind — COMMENTED** [review]
Why are all those scss related changes on this branch?

**Comment by Tianhao-Shao** [comment]
> Why are all those scss related changes on this branch?

On "Storybook Tryout", I also started the SCSS to work with Storybook. I rewrote "How to Contribute" with SCSS, I merged the Basic CSS already, so it won't affect other pages.

If I remove those SCSS files, it will mess up my  "How to Contribute" page

**Review by peggylind — COMMENTED** [review]
Do we not need the Custom.css file anymore in App.js?
I thaught the new scss is only for the How to contribute pages but the rest of the pages still need the Custom.css.

**Comment by Tianhao-Shao** [comment]
> Do we not need the Custom.css file anymore in App.js? I thaught the new scss is only for the How to contribute pages but the rest of the pages still need the Custom.css.

I merged Custom.css in SCSS files

**Review by peggylind — APPROVED** [review]

**Pull request merged**
